keys:
  - &admin age15j26ntvgzsd2h0hljkkyk4647y3htqnwj3ke2ghkp73puulgw3hssya3yu   # your personal public key
  - &host  age15j26ntvgzsd2h0hljkkyk4647y3htqnwj3ke2ghkp73puulgw3hssya3yu   # machine public key

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin
          - *host
