# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5e559f2d-f8a2-43b6-a7fa-c795a3bf07bf";
      fsType = "btrfs";
      options = [ "subvol=rootfs" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/5e559f2d-f8a2-43b6-a7fa-c795a3bf07bf";
      fsType = "btrfs";
      options = [ "subvol=snapshots" ];
    };

  fileSystems."/.swapvol" =
    { device = "/dev/disk/by-uuid/5e559f2d-f8a2-43b6-a7fa-c795a3bf07bf";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/71BA-F0C2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5e559f2d-f8a2-43b6-a7fa-c795a3bf07bf";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/5e559f2d-f8a2-43b6-a7fa-c795a3bf07bf";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/partition-root" =
    { device = "/dev/disk/by-uuid/5e559f2d-f8a2-43b6-a7fa-c795a3bf07bf";
      fsType = "btrfs";
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/5e559f2d-f8a2-43b6-a7fa-c795a3bf07bf";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
